name: Java Release Build
on:
  workflow_dispatch:
    inputs:
      scope:
        default: minor
        description: Which version number gets incremented (one of major, minor, patch)
        required: true
      stage:
        default: beta
        description: What kind of release is this? (one of beta, rc, final)
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build & Test
        # https://github.com/burrunan/gradle-cache-action
        uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Building & Testing the examples project so that we can do everything in 1 build
          build-root-directory: examples
          arguments: :plugin:assemble :plugin:check assemble check --continue --stacktrace
      - name: Publish Release
        if: github.ref == 'refs/heads/main'
        uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-root-directory: plugin
          arguments: publishPlugins --continue --stacktrace
          execution-only-caches: true
          properties: |
            reckon.scope=${{ github.event.inputs.scope }}
            reckon.stage=${{ github.event.inputs.stage }}
            gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}


